#!/bin/bash
echo "start of postinst script"
# update needed changes in apache2
a2query -m include -q
ISTAT=$?
#echo "ISTAT ${ISTAT}"
set -e
if [ ${ISTAT} -ne 0 ]
then
	sudo a2enmod include >/dev/null 2>&1
fi

rm /etc/apache2/sites-enabled/000-default.conf
ln -s /etc/apache2/sites-available/jcodatalogger.conf /etc/apache2/sites-enabled/000-default.conf
sudo service apache2 restart

echo "end of postinst script"
exit 0
